#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.

bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 50 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 51 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 52 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 53 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 54 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 55 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 56 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 57 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 58 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 59 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 60 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 61 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 62 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 63 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 64 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 65 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 66 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 67 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 68 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 69 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 70 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 71 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 72 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 73 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 74 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 75 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 76 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 77 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 78 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 79 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 80 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 81 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 82 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 83 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 84 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 85 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 86 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 87 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 88 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 89 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 90 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 91 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 92 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 93 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 94 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 95 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 96 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 97 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 98 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 99 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 100 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 101 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 102 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 103 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 104 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 105 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 106 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 107 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 108 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 109 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 110 &&
bento console --file \[v2_\ multilayer\]\ Replication\ on\ ogbn-proteins_partIII_REVISED.py --kernel pytorch 111
